sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
before_install:
  - npm install --global npm
install:
  - npm ci
script:
  - npm run lint
  - npm test
after_success:
  - npm run coveralls
cache:
  directories:
    - node_modules
